version: "3.3"
services:
  vuln:
    build: .
    ports:
      - 3036:8081
    links:
      - db
    environment:
        - PGPASSWORD=jcservice
        - PGDATABASE=jcservice
        - PGHOST=db:5432
        - PGUSER=postgres
    depends_on:
        - "db"
  db:
        image: postgres
        environment:
          - POSTGRES_PASSWORD=jcservice
          - POSTGRES_DB=jcservice